#1 gerar executável para linux
diego3g/youtube-challenge-electron-tray pull request #11
Opened 2019-07-26 15:07 UTC by acmesquita

2019-07-26 16:51 UTC, diego3g commented on .gitignore
> +package-lock.json
Por que adicionar o `package-lock.json` no .gitignore?

2019-07-26 16:53 UTC, diego3g commented on main.js
> -app.dock.hide();
Essa linha não pode ser removida, existe uma maneira de verificar se o dock não existe, dá uma olhada no #8

2019-07-26 16:53 UTC, diego3g requested changes
Vou testar no meu Ubuntu certinho e daí aprovo a PR, acho legal ajustar apenas os pontos que mencionei

2019-07-26 17:13 UTC, WilianZilv commented
Vc pode fazer if(app.dock){app.dock.hide()}, como eu fiz na minha PR do Windows

2019-07-26 17:32 UTC, acmesquita commented on .gitignore
> +package-lock.json
Por ser um arquivo gerado, não vejo sentido ir no commit.

2019-07-26 17:33 UTC, acmesquita commented on main.js
> -app.dock.hide();
Vou ajustar isso, obrigada!

2019-07-26 19:33 UTC, diego3g commented
Por que colocar as options do spawn em um array? Algum motivo específico?

2019-07-26 20:12 UTC, acmesquita commented
> Por que colocar as options do spawn em um array? Algum motivo específico?

Segundo a documentação, [https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options](url) as options devem ser passadas por array.

2019-07-26 20:18 UTC, diego3g commented
@acmesquita Na verdade lá diz que options é Object, aquele `[, options] nos parâmetros não quer dizer um array, é apenas uma forma de demonstrar que é opcional.

2019-07-26 20:40 UTC, acmesquita commented
> @acmesquita Na verdade lá diz que options é Object, aquele `[, options] nos parâmetros não quer dizer um array, é apenas uma forma de demonstrar que é opcional.

Realmente, me enganei quando coloquei o array, funcionou porque retornou um undefined para o spawn e "funcionou" no meu computador.
Descobri que por conta do PATH do meu terminal o spawn não identificava o comando 'code' e não executava o comando quando clicava. Contudo, quando deixo a opção padrão { env: process.env }, ele identifica o comando e funciona normalmente.

Dúvida, se remover o env funciona nos outros terminais e nos outros sistemas operacionais?

2019-07-27 01:05 UTC, renandecarlo commented on package.json
> +        "deb"
Não é melhor usar "snap", que tem compatibilidade maior?

2019-07-29 15:53 UTC, diego3g commented on .gitignore
> +package-lock.json
Estamos usando Yarn nesse pacote e por isso usamos o yarn.lock e por isso não é legal você incluir o package-lock.json de qualquer forma, porém os arquivos `.lock` por mais que são gerados, eles devem ir ao Git, isso porque armazenam cache para acelerar a instalação dos pacotes do zero :)

2019-07-29 15:54 UTC, diego3g commented on package.json
> +        "deb"
Acredito que podemos gerar até mais de um formato, o que acham?

2019-07-29 15:55 UTC, diego3g commented
@acmesquita O `env` é essencial para funcionar em produção. Sem ele até funciona no Mac em desenvolvimento mas em produção simplesmente não rola, ele não reconhece o caminho para meu executável do `code`. Acho que seria legal só ajustarmos o `package-lock.json` (pode removê-lo por completo, nem precisa incluir no ignore). Podemos também aceitar mais opções de executáveis pro Linux além do `.deb`?

2019-07-29 16:34 UTC, acmesquita commented on .gitignore
> +package-lock.json
Entendi, obrigada pela explicação... =D Irei remover e adicionar mais opções de downloads.

2019-07-29 16:58 UTC, diego3g commented
Executei um merge para sincronizar com a versão na master que havia sido atualizada por outra PR, com isso acredito que possamos aceitar. Obrigado pela contribuição @acmesquita :)

2019-07-29 16:58 UTC, merged

2019-07-29 17:01 UTC, diego3g commented
@acmesquita Rodei o `yarn dist` aqui e não está gerando os artefatos `.dev`, apenas os de Mac, sabe se preciso fazer algo a mais?

2019-07-29 17:26 UTC, acmesquita commented
@diego3g, o `electron-builder` reconhece a plataforma que está sendo gerado os pacotes como na imagem abaixo

![image](https://user-images.githubusercontent.com/15862643/62068646-d1293080-b20c-11e9-99ff-4bec8df2e9b6.png)

Para rodar para a plataforma linux é preciso rodar o comando com a flag `--linux`. Não rodei no mac, mas acredito que rodando o comando `npm run dist:linux` possa gerar os arquivos `.deb`, `.snap` e `.rpm`.

2019-07-29 17:45 UTC, diego3g commented
@acmesquita Consegui rodar também com o comando `yarn dist -mwl` que gerou executável para Mac, Windows e Linux.